"""Deterministic check that a rollback's correction_message survives all the
way from RollbackManager into a saved run record, without depending on a live
model call landing above ROLLBACK_SEVERITY_THRESHOLD by chance (real runs
have shown near-identical token_explosion anomalies scoring both sides of the
0.45 line — see the run comparing ratio 2.32 (0.4507, rolled back) vs.
ratio 2.20 (0.4002, did not) on 2026-07-21).

This builds a synthetic-but-realistic trajectory and anomaly set, drives it
through the real RollbackManager (no mocking of scorer/correction logic —
only the trajectory/anomaly inputs are synthetic), and saves the result via
the real monitor.run_store.save_run(), so it shows up in the dashboard's
History tab exactly like a live run would. Run this, then open the dashboard,
go to History, and load the newest entry to see "Rollback history" populated
with real correction_message text for three different anomaly types.

Run with:
    python3 tests/verify_correction_message_display.py
"""

import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from monitor.rollback import RollbackManager
from monitor.run_store import save_run

TASK = (
    "Read the file tasks/buggy_add.py, find the bug, and fix it. Then create "
    "a new file tasks/buggy_add_tests.py that copies the corrected add() "
    "function into itself and includes 5 self-contained test cases."
)


class FakeLogger:
    """attempt_rollback only calls logger.start_new_branch(point) to get a
    new branch id — it doesn't touch trajectory storage, so a trivial stub
    is enough without pulling in the real TrajectoryLogger."""
    def __init__(self):
        self._next_branch = 1

    def start_new_branch(self, rollback_point):
        branch_id = self._next_branch
        self._next_branch += 1
        return branch_id


def main():
    rollback_manager = RollbackManager()
    logger = FakeLogger()

    trajectory = [
        {"step_number": 1, "tool_used": "read_file"},
        {"step_number": 2, "tool_used": "write_file"},
    ]

    # Three separate attempts, one per anomaly type that has its own
    # CORRECTION_TEMPLATES entry — proves the fix isn't specific to
    # token_explosion (the only type that's fired live so far).
    scenarios = [
        ("token_explosion", [{
            "type": "token_explosion", "step": 2, "token_count": 950,
            "rolling_average": 420.0, "ratio": 2.26, "detection_method": "rolling_average",
        }], 0.55),
        ("goal_drift", [{
            "type": "goal_drift", "step": 2, "similarity": 0.31,
        }], 0.7),
        ("infinite_loop", [{
            "type": "infinite_loop", "step": 2,
            "repeated_signature": [["read_file", "{'filepath': 'x.py'}", "content"]],
            "cycle_length": 1, "repetition_count": 2,
        }], 0.9),
    ]

    for label, anomalies, severity in scenarios:
        result = rollback_manager.attempt_rollback(
            anomalies=anomalies,
            severity=severity,
            trajectory=trajectory,
            original_goal=TASK,
            logger=logger,
        )
        assert result["status"] == "retrying", f"{label}: expected a retry, got {result['status']}"
        print(f"[{label}] correction_message: {result['correction_message']!r}")

    for entry in rollback_manager.rollback_history:
        assert "correction_message" in entry, f"correction_message missing from persisted entry: {entry}"
    print(f"\nOK — all {len(rollback_manager.rollback_history)} rollback_history entries carry correction_message.")

    fake_result = {
        "status": "escalated",
        "message": "",
        "warning": "Synthetic run generated by tests/verify_correction_message_display.py to exercise the dashboard's Rollback history display — not a real agent run.",
        "trajectory": trajectory,
        "cost_summary": {
            "total_tokens": 1875, "useful_tokens": 1875,
            "rollback_count": len(rollback_manager.rollback_history),
            "tokens_wasted_on_rollbacks": 0, "trim_count": 0,
            "tokens_wasted_on_trims": 0, "cost_multiplier": 1.0,
        },
        "anomalies_by_step": {"2": [a for _, anomalies, _ in scenarios for a in anomalies]},
        "rollback_history": rollback_manager.rollback_history,
    }
    run_id = save_run(TASK, fake_result)
    print(f"\nSaved synthetic run: {run_id}")
    print("Open the dashboard, go to the History tab, load this run, and expand "
          "each attempt under 'Rollback history' to see the correction message.")


if __name__ == "__main__":
    main()
